//! Generated `vaults/<vault>/index.md` (§4.4). Built by code from page frontmatter, never by the LLM.

pub const GENERATED_MARKER: &str =
    "<!-- generated by daftar: do not edit; rebuilt from page frontmatter -->";

pub fn empty_index(title_en: &str, title_fa: &str) -> String {
    format!("# {title_en} · {title_fa}\n\n{GENERATED_MARKER}\n\n_No pages yet._\n")
}
