// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/info.dart';
import 'api/library.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInfoInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 12048493;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'daftar_bridge',
        ioDirectory: '../core/daftar_bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiLibraryLibraryHandleCapturePhoto({
    required LibraryHandle that,
    required List<int> bytes,
    String? note,
    String? vaultHint,
  });

  Future<String> crateApiLibraryLibraryHandleCaptureText({
    required LibraryHandle that,
    required String text,
    String? vaultHint,
  });

  Future<String> crateApiLibraryLibraryHandleCaptureVoice({
    required LibraryHandle that,
    required String audioPath,
    String? vaultHint,
  });

  Future<List<Capture>> crateApiLibraryLibraryHandleDay({
    required LibraryHandle that,
    required int year,
    required int month,
    required int day,
  });

  Future<bool> crateApiLibraryLibraryHandleDiscard({
    required LibraryHandle that,
    required String id,
  });

  Future<LibraryHandle> crateApiLibraryLibraryHandleOpen({
    required String root,
  });

  Future<void> crateApiLibraryLibraryHandleSetRemote({
    required LibraryHandle that,
    required String url,
  });

  Future<RepoStatus> crateApiLibraryLibraryHandleStatus({
    required LibraryHandle that,
  });

  Future<SyncResult> crateApiLibraryLibraryHandleSync({
    required LibraryHandle that,
    required Auth auth,
  });

  Future<List<Vault>> crateApiLibraryLibraryHandleVaults({
    required LibraryHandle that,
  });

  Future<void> crateApiLibraryCloneLibrary({
    required String url,
    required String root,
    required Auth auth,
    required String branch,
    required String deviceName,
    required String platform,
  });

  CoreInfo crateApiInfoCoreInfo();

  Future<SshKeyPair> crateApiLibraryGenerateSshKey({required String comment});

  Future<void> crateApiInfoInitApp();

  Future<void> crateApiLibraryInitLibrary({
    required String root,
    required String deviceName,
    required String platform,
  });

  bool crateApiLibraryLibraryReady({required String root});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LibraryHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LibraryHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LibraryHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiLibraryLibraryHandleCapturePhoto({
    required LibraryHandle that,
    required List<int> bytes,
    String? note,
    String? vaultHint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(note, serializer);
          sse_encode_opt_String(vaultHint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryLibraryHandleCapturePhotoConstMeta,
        argValues: [that, bytes, note, vaultHint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryHandleCapturePhotoConstMeta =>
      const TaskConstMeta(
        debugName: "LibraryHandle_capture_photo",
        argNames: ["that", "bytes", "note", "vaultHint"],
      );

  @override
  Future<String> crateApiLibraryLibraryHandleCaptureText({
    required LibraryHandle that,
    required String text,
    String? vaultHint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
            that,
            serializer,
          );
          sse_encode_String(text, serializer);
          sse_encode_opt_String(vaultHint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryLibraryHandleCaptureTextConstMeta,
        argValues: [that, text, vaultHint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryHandleCaptureTextConstMeta =>
      const TaskConstMeta(
        debugName: "LibraryHandle_capture_text",
        argNames: ["that", "text", "vaultHint"],
      );

  @override
  Future<String> crateApiLibraryLibraryHandleCaptureVoice({
    required LibraryHandle that,
    required String audioPath,
    String? vaultHint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
            that,
            serializer,
          );
          sse_encode_String(audioPath, serializer);
          sse_encode_opt_String(vaultHint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryLibraryHandleCaptureVoiceConstMeta,
        argValues: [that, audioPath, vaultHint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryHandleCaptureVoiceConstMeta =>
      const TaskConstMeta(
        debugName: "LibraryHandle_capture_voice",
        argNames: ["that", "audioPath", "vaultHint"],
      );

  @override
  Future<List<Capture>> crateApiLibraryLibraryHandleDay({
    required LibraryHandle that,
    required int year,
    required int month,
    required int day,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
            that,
            serializer,
          );
          sse_encode_i_32(year, serializer);
          sse_encode_u_8(month, serializer);
          sse_encode_u_8(day, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_capture,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryLibraryHandleDayConstMeta,
        argValues: [that, year, month, day],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryHandleDayConstMeta =>
      const TaskConstMeta(
        debugName: "LibraryHandle_day",
        argNames: ["that", "year", "month", "day"],
      );

  @override
  Future<bool> crateApiLibraryLibraryHandleDiscard({
    required LibraryHandle that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryLibraryHandleDiscardConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryHandleDiscardConstMeta =>
      const TaskConstMeta(
        debugName: "LibraryHandle_discard",
        argNames: ["that", "id"],
      );

  @override
  Future<LibraryHandle> crateApiLibraryLibraryHandleOpen({
    required String root,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryLibraryHandleOpenConstMeta,
        argValues: [root],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryHandleOpenConstMeta =>
      const TaskConstMeta(debugName: "LibraryHandle_open", argNames: ["root"]);

  @override
  Future<void> crateApiLibraryLibraryHandleSetRemote({
    required LibraryHandle that,
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
            that,
            serializer,
          );
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryLibraryHandleSetRemoteConstMeta,
        argValues: [that, url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryHandleSetRemoteConstMeta =>
      const TaskConstMeta(
        debugName: "LibraryHandle_set_remote",
        argNames: ["that", "url"],
      );

  @override
  Future<RepoStatus> crateApiLibraryLibraryHandleStatus({
    required LibraryHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_repo_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryLibraryHandleStatusConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryHandleStatusConstMeta =>
      const TaskConstMeta(
        debugName: "LibraryHandle_status",
        argNames: ["that"],
      );

  @override
  Future<SyncResult> crateApiLibraryLibraryHandleSync({
    required LibraryHandle that,
    required Auth auth,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
            that,
            serializer,
          );
          sse_encode_box_autoadd_auth(auth, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryLibraryHandleSyncConstMeta,
        argValues: [that, auth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryHandleSyncConstMeta =>
      const TaskConstMeta(
        debugName: "LibraryHandle_sync",
        argNames: ["that", "auth"],
      );

  @override
  Future<List<Vault>> crateApiLibraryLibraryHandleVaults({
    required LibraryHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_vault,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryLibraryHandleVaultsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryHandleVaultsConstMeta =>
      const TaskConstMeta(
        debugName: "LibraryHandle_vaults",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiLibraryCloneLibrary({
    required String url,
    required String root,
    required Auth auth,
    required String branch,
    required String deviceName,
    required String platform,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(root, serializer);
          sse_encode_box_autoadd_auth(auth, serializer);
          sse_encode_String(branch, serializer);
          sse_encode_String(deviceName, serializer);
          sse_encode_String(platform, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryCloneLibraryConstMeta,
        argValues: [url, root, auth, branch, deviceName, platform],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryCloneLibraryConstMeta =>
      const TaskConstMeta(
        debugName: "clone_library",
        argNames: ["url", "root", "auth", "branch", "deviceName", "platform"],
      );

  @override
  CoreInfo crateApiInfoCoreInfo() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_core_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInfoCoreInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInfoCoreInfoConstMeta =>
      const TaskConstMeta(debugName: "core_info", argNames: []);

  @override
  Future<SshKeyPair> crateApiLibraryGenerateSshKey({required String comment}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comment, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ssh_key_pair,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryGenerateSshKeyConstMeta,
        argValues: [comment],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryGenerateSshKeyConstMeta =>
      const TaskConstMeta(debugName: "generate_ssh_key", argNames: ["comment"]);

  @override
  Future<void> crateApiInfoInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInfoInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInfoInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiLibraryInitLibrary({
    required String root,
    required String deviceName,
    required String platform,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(deviceName, serializer);
          sse_encode_String(platform, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryInitLibraryConstMeta,
        argValues: [root, deviceName, platform],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryInitLibraryConstMeta => const TaskConstMeta(
    debugName: "init_library",
    argNames: ["root", "deviceName", "platform"],
  );

  @override
  bool crateApiLibraryLibraryReady({required String root}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryLibraryReadyConstMeta,
        argValues: [root],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryReadyConstMeta =>
      const TaskConstMeta(debugName: "library_ready", argNames: ["root"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LibraryHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LibraryHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  LibraryHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LibraryHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LibraryHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LibraryHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LibraryHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LibraryHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Auth dco_decode_auth(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Auth(
      kind: dco_decode_auth_kind(arr[0]),
      username: dco_decode_opt_String(arr[1]),
      secret: dco_decode_String(arr[2]),
      passphrase: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  AuthKind dco_decode_auth_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AuthKind.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Auth dco_decode_box_autoadd_auth(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_auth(raw);
  }

  @protected
  Capture dco_decode_capture(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return Capture(
      id: dco_decode_String(arr[0]),
      kind: dco_decode_raw_kind(arr[1]),
      capturedAt: dco_decode_String(arr[2]),
      device: dco_decode_String(arr[3]),
      text: dco_decode_String(arr[4]),
      vaultHint: dco_decode_opt_String(arr[5]),
      images: dco_decode_list_String(arr[6]),
      stage: dco_decode_stage(arr[7]),
      problem: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  CoreInfo dco_decode_core_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CoreInfo(
      appName: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      repoSchemaVersion: dco_decode_u_32(arr[2]),
      target: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Capture> dco_decode_list_capture(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_capture).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Vault> dco_decode_list_vault(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_vault).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RawKind dco_decode_raw_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RawKind.values[raw as int];
  }

  @protected
  RepoStatus dco_decode_repo_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RepoStatus(
      uncommitted: dco_decode_u_32(arr[0]),
      unpushed: dco_decode_u_32(arr[1]),
      hasRemote: dco_decode_bool(arr[2]),
      branch: dco_decode_String(arr[3]),
      remoteUrl: dco_decode_opt_String(arr[4]),
      deviceId: dco_decode_String(arr[5]),
      deviceName: dco_decode_String(arr[6]),
      root: dco_decode_String(arr[7]),
    );
  }

  @protected
  SshKeyPair dco_decode_ssh_key_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SshKeyPair(
      privateOpenssh: dco_decode_String(arr[0]),
      publicOpenssh: dco_decode_String(arr[1]),
    );
  }

  @protected
  Stage dco_decode_stage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Stage.values[raw as int];
  }

  @protected
  SyncResult dco_decode_sync_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SyncResult(
      state: dco_decode_sync_state(arr[0]),
      message: dco_decode_opt_String(arr[1]),
      pulled: dco_decode_u_32(arr[2]),
      pushed: dco_decode_u_32(arr[3]),
      conflicts: dco_decode_list_String(arr[4]),
      replays: dco_decode_u_32(arr[5]),
      changedPaths: dco_decode_list_String(arr[6]),
    );
  }

  @protected
  SyncState dco_decode_sync_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncState.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Vault dco_decode_vault(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Vault(
      id: dco_decode_String(arr[0]),
      titleEn: dco_decode_String(arr[1]),
      titleFa: dco_decode_String(arr[2]),
      fiction: dco_decode_bool(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  LibraryHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LibraryHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LibraryHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LibraryHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LibraryHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LibraryHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Auth sse_decode_auth(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_auth_kind(deserializer);
    var var_username = sse_decode_opt_String(deserializer);
    var var_secret = sse_decode_String(deserializer);
    var var_passphrase = sse_decode_opt_String(deserializer);
    return Auth(
      kind: var_kind,
      username: var_username,
      secret: var_secret,
      passphrase: var_passphrase,
    );
  }

  @protected
  AuthKind sse_decode_auth_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AuthKind.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Auth sse_decode_box_autoadd_auth(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_auth(deserializer));
  }

  @protected
  Capture sse_decode_capture(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_kind = sse_decode_raw_kind(deserializer);
    var var_capturedAt = sse_decode_String(deserializer);
    var var_device = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_vaultHint = sse_decode_opt_String(deserializer);
    var var_images = sse_decode_list_String(deserializer);
    var var_stage = sse_decode_stage(deserializer);
    var var_problem = sse_decode_opt_String(deserializer);
    return Capture(
      id: var_id,
      kind: var_kind,
      capturedAt: var_capturedAt,
      device: var_device,
      text: var_text,
      vaultHint: var_vaultHint,
      images: var_images,
      stage: var_stage,
      problem: var_problem,
    );
  }

  @protected
  CoreInfo sse_decode_core_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appName = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_repoSchemaVersion = sse_decode_u_32(deserializer);
    var var_target = sse_decode_String(deserializer);
    return CoreInfo(
      appName: var_appName,
      version: var_version,
      repoSchemaVersion: var_repoSchemaVersion,
      target: var_target,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Capture> sse_decode_list_capture(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Capture>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_capture(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Vault> sse_decode_list_vault(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Vault>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_vault(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RawKind sse_decode_raw_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RawKind.values[inner];
  }

  @protected
  RepoStatus sse_decode_repo_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uncommitted = sse_decode_u_32(deserializer);
    var var_unpushed = sse_decode_u_32(deserializer);
    var var_hasRemote = sse_decode_bool(deserializer);
    var var_branch = sse_decode_String(deserializer);
    var var_remoteUrl = sse_decode_opt_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_root = sse_decode_String(deserializer);
    return RepoStatus(
      uncommitted: var_uncommitted,
      unpushed: var_unpushed,
      hasRemote: var_hasRemote,
      branch: var_branch,
      remoteUrl: var_remoteUrl,
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      root: var_root,
    );
  }

  @protected
  SshKeyPair sse_decode_ssh_key_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_privateOpenssh = sse_decode_String(deserializer);
    var var_publicOpenssh = sse_decode_String(deserializer);
    return SshKeyPair(
      privateOpenssh: var_privateOpenssh,
      publicOpenssh: var_publicOpenssh,
    );
  }

  @protected
  Stage sse_decode_stage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Stage.values[inner];
  }

  @protected
  SyncResult sse_decode_sync_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_sync_state(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    var var_pulled = sse_decode_u_32(deserializer);
    var var_pushed = sse_decode_u_32(deserializer);
    var var_conflicts = sse_decode_list_String(deserializer);
    var var_replays = sse_decode_u_32(deserializer);
    var var_changedPaths = sse_decode_list_String(deserializer);
    return SyncResult(
      state: var_state,
      message: var_message,
      pulled: var_pulled,
      pushed: var_pushed,
      conflicts: var_conflicts,
      replays: var_replays,
      changedPaths: var_changedPaths,
    );
  }

  @protected
  SyncState sse_decode_sync_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SyncState.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  Vault sse_decode_vault(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_titleEn = sse_decode_String(deserializer);
    var var_titleFa = sse_decode_String(deserializer);
    var var_fiction = sse_decode_bool(deserializer);
    return Vault(
      id: var_id,
      titleEn: var_titleEn,
      titleFa: var_titleFa,
      fiction: var_fiction,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
    LibraryHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LibraryHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
    LibraryHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LibraryHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryHandle(
    LibraryHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LibraryHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth(Auth self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_auth_kind(self.kind, serializer);
    sse_encode_opt_String(self.username, serializer);
    sse_encode_String(self.secret, serializer);
    sse_encode_opt_String(self.passphrase, serializer);
  }

  @protected
  void sse_encode_auth_kind(AuthKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_auth(Auth self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_auth(self, serializer);
  }

  @protected
  void sse_encode_capture(Capture self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_raw_kind(self.kind, serializer);
    sse_encode_String(self.capturedAt, serializer);
    sse_encode_String(self.device, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_opt_String(self.vaultHint, serializer);
    sse_encode_list_String(self.images, serializer);
    sse_encode_stage(self.stage, serializer);
    sse_encode_opt_String(self.problem, serializer);
  }

  @protected
  void sse_encode_core_info(CoreInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.appName, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_u_32(self.repoSchemaVersion, serializer);
    sse_encode_String(self.target, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_capture(List<Capture> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_capture(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_vault(List<Vault> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_vault(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_raw_kind(RawKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_repo_status(RepoStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.uncommitted, serializer);
    sse_encode_u_32(self.unpushed, serializer);
    sse_encode_bool(self.hasRemote, serializer);
    sse_encode_String(self.branch, serializer);
    sse_encode_opt_String(self.remoteUrl, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.root, serializer);
  }

  @protected
  void sse_encode_ssh_key_pair(SshKeyPair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.privateOpenssh, serializer);
    sse_encode_String(self.publicOpenssh, serializer);
  }

  @protected
  void sse_encode_stage(Stage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sync_result(SyncResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sync_state(self.state, serializer);
    sse_encode_opt_String(self.message, serializer);
    sse_encode_u_32(self.pulled, serializer);
    sse_encode_u_32(self.pushed, serializer);
    sse_encode_list_String(self.conflicts, serializer);
    sse_encode_u_32(self.replays, serializer);
    sse_encode_list_String(self.changedPaths, serializer);
  }

  @protected
  void sse_encode_sync_state(SyncState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vault(Vault self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.titleEn, serializer);
    sse_encode_String(self.titleFa, serializer);
    sse_encode_bool(self.fiction, serializer);
  }
}

@sealed
class LibraryHandleImpl extends RustOpaque implements LibraryHandle {
  // Not to be used by end users
  LibraryHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LibraryHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LibraryHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LibraryHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LibraryHandlePtr,
  );

  Future<String> capturePhoto({
    required List<int> bytes,
    String? note,
    String? vaultHint,
  }) => RustLib.instance.api.crateApiLibraryLibraryHandleCapturePhoto(
    that: this,
    bytes: bytes,
    note: note,
    vaultHint: vaultHint,
  );

  Future<String> captureText({required String text, String? vaultHint}) =>
      RustLib.instance.api.crateApiLibraryLibraryHandleCaptureText(
        that: this,
        text: text,
        vaultHint: vaultHint,
      );

  Future<String> captureVoice({required String audioPath, String? vaultHint}) =>
      RustLib.instance.api.crateApiLibraryLibraryHandleCaptureVoice(
        that: this,
        audioPath: audioPath,
        vaultHint: vaultHint,
      );

  /// Captures of the given local date, oldest first.
  Future<List<Capture>> day({
    required int year,
    required int month,
    required int day,
  }) => RustLib.instance.api.crateApiLibraryLibraryHandleDay(
    that: this,
    year: year,
    month: month,
    day: day,
  );

  Future<bool> discard({required String id}) => RustLib.instance.api
      .crateApiLibraryLibraryHandleDiscard(that: this, id: id);

  Future<void> setRemote({required String url}) => RustLib.instance.api
      .crateApiLibraryLibraryHandleSetRemote(that: this, url: url);

  Future<RepoStatus> status() =>
      RustLib.instance.api.crateApiLibraryLibraryHandleStatus(that: this);

  Future<SyncResult> sync_({required Auth auth}) => RustLib.instance.api
      .crateApiLibraryLibraryHandleSync(that: this, auth: auth);

  Future<List<Vault>> vaults() =>
      RustLib.instance.api.crateApiLibraryLibraryHandleVaults(that: this);
}
