// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `from_config`, `keys`, `role_dto`, `to_config`, `warning_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// The public endpoint used when a provider's base URL is left empty.
String defaultBaseUrl({required ProviderKindDto kind}) =>
    RustLib.instance.api.crateApiAiDefaultBaseUrl(kind: kind);

/// Capability warning for a model typed or picked for `role`, before it is saved.
CapabilityWarning? capabilityWarning({
  required ModelRole role,
  required String model,
}) =>
    RustLib.instance.api.crateApiAiCapabilityWarning(role: role, model: model);

/// Lists a provider's models (`/models`). Works for unsaved providers, so the key can be checked
/// while the provider is being set up.
Future<List<String>> listModels({
  required AiProvider provider,
  String? apiKey,
}) => RustLib.instance.api.crateApiAiListModels(
  provider: provider,
  apiKey: apiKey,
);

class AiProvider {
  /// Empty when creating a new provider.
  final String id;
  final String name;
  final ProviderKindDto kind;

  /// Empty means the provider's public endpoint.
  final String baseUrl;
  final List<HttpHeader> headers;
  final int timeoutS;

  const AiProvider({
    required this.id,
    required this.name,
    required this.kind,
    required this.baseUrl,
    required this.headers,
    required this.timeoutS,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      baseUrl.hashCode ^
      headers.hashCode ^
      timeoutS.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiProvider &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          kind == other.kind &&
          baseUrl == other.baseUrl &&
          headers == other.headers &&
          timeoutS == other.timeoutS;
}

class AiSettings {
  final List<AiProvider> providers;
  final List<RoleSetting> roles;

  const AiSettings({required this.providers, required this.roles});

  @override
  int get hashCode => providers.hashCode ^ roles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiSettings &&
          runtimeType == other.runtimeType &&
          providers == other.providers &&
          roles == other.roles;
}

/// An API key for one provider, read from secure storage by the app.
class ApiKey {
  final String providerId;
  final String key;

  const ApiKey({required this.providerId, required this.key});

  @override
  int get hashCode => providerId.hashCode ^ key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiKey &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          key == other.key;
}

enum CapabilityWarning {
  noVision,
  notSpeechToText,
  notTextToSpeech,
  notEmbedding,
  notConversational,
}

class HttpHeader {
  final String name;
  final String value;

  const HttpHeader({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpHeader &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

enum JobKindDto { transcribe, describe, ingest, other }

class JobOutcome {
  final JobKindDto kind;
  final String? rawId;
  final JobStateDto state;
  final String? message;
  final ModelRole? waitingFor;

  const JobOutcome({
    required this.kind,
    this.rawId,
    required this.state,
    this.message,
    this.waitingFor,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      rawId.hashCode ^
      state.hashCode ^
      message.hashCode ^
      waitingFor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JobOutcome &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          rawId == other.rawId &&
          state == other.state &&
          message == other.message &&
          waitingFor == other.waitingFor;
}

enum JobStateDto { queued, running, done, failed }

enum ModelRole {
  router,
  ingest,
  chat,
  voice,
  vision,
  reflect,
  lint,
  stt,
  tts,
  embedding,
}

class ProbeOutcome {
  final bool ok;
  final int latencyMs;

  /// Short reply on success ("OK", "no speech (as expected)"), one human sentence on failure.
  final String detail;

  const ProbeOutcome({
    required this.ok,
    required this.latencyMs,
    required this.detail,
  });

  @override
  int get hashCode => ok.hashCode ^ latencyMs.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProbeOutcome &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          latencyMs == other.latencyMs &&
          detail == other.detail;
}

enum ProviderKindDto { openaiCompatible, anthropic, gemini }

class RoleSetting {
  final ModelRole role;

  /// Provider and model this role uses, possibly through a fallback role.
  final String? providerId;
  final String? model;

  /// Set when the role is not configured itself and borrows another role's setting.
  final ModelRole? inheritedFrom;

  /// Heuristic capability mismatch, in English; the app shows its own localized sentence.
  final CapabilityWarning? warning;

  const RoleSetting({
    required this.role,
    this.providerId,
    this.model,
    this.inheritedFrom,
    this.warning,
  });

  @override
  int get hashCode =>
      role.hashCode ^
      providerId.hashCode ^
      model.hashCode ^
      inheritedFrom.hashCode ^
      warning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoleSetting &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          providerId == other.providerId &&
          model == other.model &&
          inheritedFrom == other.inheritedFrom &&
          warning == other.warning;
}

class RunSummary {
  final List<JobOutcome> jobs;

  /// Jobs still queued (e.g. waiting for a retry or a model to be set up).
  final bool pending;

  const RunSummary({required this.jobs, required this.pending});

  @override
  int get hashCode => jobs.hashCode ^ pending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RunSummary &&
          runtimeType == other.runtimeType &&
          jobs == other.jobs &&
          pending == other.pending;
}
