// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `event`, `scope`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

class AnswerCitation {
  final String target;
  final String? label;

  /// `None`: the answer cited something that does not exist (shown as plain text).
  final String? path;

  const AnswerCitation({required this.target, this.label, this.path});

  @override
  int get hashCode => target.hashCode ^ label.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnswerCitation &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          label == other.label &&
          path == other.path;
}

class AskAnswer {
  final String text;
  final List<AnswerCitation> citations;
  final bool needsHelp;
  final String model;
  final BigInt inputTokens;
  final BigInt outputTokens;
  final double? costUsd;

  const AskAnswer({
    required this.text,
    required this.citations,
    required this.needsHelp,
    required this.model,
    required this.inputTokens,
    required this.outputTokens,
    this.costUsd,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      citations.hashCode ^
      needsHelp.hashCode ^
      model.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode ^
      costUsd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskAnswer &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          citations == other.citations &&
          needsHelp == other.needsHelp &&
          model == other.model &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          costUsd == other.costUsd;
}

class AskEvent {
  final AskEventKind kind;

  /// The delta, or the failure sentence.
  final String? text;
  final AskAnswer? answer;

  const AskEvent({required this.kind, this.text, this.answer});

  @override
  int get hashCode => kind.hashCode ^ text.hashCode ^ answer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text &&
          answer == other.answer;
}

enum AskEventKind {
  /// Streamed text as it arrives (includes text the model writes between tool calls).
  delta,
  done,
  failed,
}

class AskImage {
  final String mediaType;
  final Uint8List bytes;

  const AskImage({required this.mediaType, required this.bytes});

  @override
  int get hashCode => mediaType.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskImage &&
          runtimeType == other.runtimeType &&
          mediaType == other.mediaType &&
          bytes == other.bytes;
}

class AskScopeDto {
  final AskScopeKind kind;

  /// Vault id or story slug.
  final String? id;

  const AskScopeDto({required this.kind, this.id});

  @override
  int get hashCode => kind.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskScopeDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          id == other.id;
}

enum AskScopeKind { all, vault, story }

class AskTurn {
  final String question;
  final String answer;

  const AskTurn({required this.question, required this.answer});

  @override
  int get hashCode => question.hashCode ^ answer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskTurn &&
          runtimeType == other.runtimeType &&
          question == other.question &&
          answer == other.answer;
}
