// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `event`, `scope`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`

/// Help to show on the "Talk to someone" card (§4.7), for an ISO country code ("" = international).
List<Helpline> helplines({required String country}) =>
    RustLib.instance.api.crateApiAskHelplines(country: country);

class AnswerCitation {
  final String target;
  final String? label;

  /// `None`: the answer cited something that does not exist (shown as plain text).
  final String? path;

  const AnswerCitation({required this.target, this.label, this.path});

  @override
  int get hashCode => target.hashCode ^ label.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnswerCitation &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          label == other.label &&
          path == other.path;
}

class AskAnswer {
  final String text;
  final List<AnswerCitation> citations;
  final bool needsHelp;
  final String model;
  final BigInt inputTokens;
  final BigInt outputTokens;
  final double? costUsd;

  const AskAnswer({
    required this.text,
    required this.citations,
    required this.needsHelp,
    required this.model,
    required this.inputTokens,
    required this.outputTokens,
    this.costUsd,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      citations.hashCode ^
      needsHelp.hashCode ^
      model.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode ^
      costUsd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskAnswer &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          citations == other.citations &&
          needsHelp == other.needsHelp &&
          model == other.model &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          costUsd == other.costUsd;
}

class AskEvent {
  final AskEventKind kind;

  /// The delta, or the failure sentence.
  final String? text;
  final AskAnswer? answer;
  final ToolApproval? approval;

  const AskEvent({required this.kind, this.text, this.answer, this.approval});

  @override
  int get hashCode =>
      kind.hashCode ^ text.hashCode ^ answer.hashCode ^ approval.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text &&
          answer == other.answer &&
          approval == other.approval;
}

enum AskEventKind {
  /// Streamed text as it arrives (includes text the model writes between tool calls).
  delta,

  /// An outside tool wants to run; answer with `answer_tool_approval` (§10).
  approval,
  done,
  failed,
}

class AskImage {
  final String mediaType;
  final Uint8List bytes;

  const AskImage({required this.mediaType, required this.bytes});

  @override
  int get hashCode => mediaType.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskImage &&
          runtimeType == other.runtimeType &&
          mediaType == other.mediaType &&
          bytes == other.bytes;
}

class AskScopeDto {
  final AskScopeKind kind;

  /// Vault id or story slug.
  final String? id;

  const AskScopeDto({required this.kind, this.id});

  @override
  int get hashCode => kind.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskScopeDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          id == other.id;
}

enum AskScopeKind { all, vault, story }

class AskTurn {
  final String question;
  final String answer;

  const AskTurn({required this.question, required this.answer});

  @override
  int get hashCode => question.hashCode ^ answer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AskTurn &&
          runtimeType == other.runtimeType &&
          question == other.question &&
          answer == other.answer;
}

class Helpline {
  final String nameEn;
  final String nameFa;
  final String phone;
  final String url;

  const Helpline({
    required this.nameEn,
    required this.nameFa,
    required this.phone,
    required this.url,
  });

  @override
  int get hashCode =>
      nameEn.hashCode ^ nameFa.hashCode ^ phone.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Helpline &&
          runtimeType == other.runtimeType &&
          nameEn == other.nameEn &&
          nameFa == other.nameFa &&
          phone == other.phone &&
          url == other.url;
}

/// Credentials of one MCP server on this device (JSON from secure storage).
class McpSecret {
  final String serverId;
  final String secretsJson;

  const McpSecret({required this.serverId, required this.secretsJson});

  @override
  int get hashCode => serverId.hashCode ^ secretsJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McpSecret &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          secretsJson == other.secretsJson;
}

/// A tool call waiting for the user's yes or no.
class ToolApproval {
  final String requestId;
  final String serverName;
  final String tool;

  /// The arguments as pretty JSON.
  final String arguments;
  final bool readOnly;

  const ToolApproval({
    required this.requestId,
    required this.serverName,
    required this.tool,
    required this.arguments,
    required this.readOnly,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      serverName.hashCode ^
      tool.hashCode ^
      arguments.hashCode ^
      readOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToolApproval &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          serverName == other.serverName &&
          tool == other.tool &&
          arguments == other.arguments &&
          readOnly == other.readOnly;
}
