// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `claim_dto`, `err`, `op_dto`, `undo_dto`

enum CardKind {
  claim,
  routing,
  lint,
  syncConflict,
  schema,
  question,
  humanEdit,
}

class ClaimInfo {
  final String id;
  final String text;
  final String status;
  final String? confidence;
  final List<String> sources;

  const ClaimInfo({
    required this.id,
    required this.text,
    required this.status,
    this.confidence,
    required this.sources,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      text.hashCode ^
      status.hashCode ^
      confidence.hashCode ^
      sources.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClaimInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          status == other.status &&
          confidence == other.confidence &&
          sources == other.sources;
}

class DiffLine {
  final DiffLineKind kind;
  final String text;

  const DiffLine({required this.kind, required this.text});

  @override
  int get hashCode => kind.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffLine &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text;
}

enum DiffLineKind { context, added, removed, gap }

enum OpKind { ingest, undo, compensate, review, saveAnswer, lint, reflect }

class Operation {
  final String opId;
  final OpKind kind;

  /// English one-line summary from the ledger (the app builds its own localized line).
  final String summary;
  final String startedAt;
  final String device;
  final List<String> vaults;
  final int pagesCreated;
  final int pagesUpdated;
  final int claimsAdded;
  final List<String> sources;
  final String? reverts;
  final String? replayedFrom;
  final bool undone;
  final String? note;
  final String? forcedVault;
  final List<String> models;
  final BigInt inputTokens;
  final BigInt outputTokens;
  final double? costUsd;

  /// Why the vaults were chosen (router targets with reasons and confidences).
  final List<RouteTarget> route;

  const Operation({
    required this.opId,
    required this.kind,
    required this.summary,
    required this.startedAt,
    required this.device,
    required this.vaults,
    required this.pagesCreated,
    required this.pagesUpdated,
    required this.claimsAdded,
    required this.sources,
    this.reverts,
    this.replayedFrom,
    required this.undone,
    this.note,
    this.forcedVault,
    required this.models,
    required this.inputTokens,
    required this.outputTokens,
    this.costUsd,
    required this.route,
  });

  @override
  int get hashCode =>
      opId.hashCode ^
      kind.hashCode ^
      summary.hashCode ^
      startedAt.hashCode ^
      device.hashCode ^
      vaults.hashCode ^
      pagesCreated.hashCode ^
      pagesUpdated.hashCode ^
      claimsAdded.hashCode ^
      sources.hashCode ^
      reverts.hashCode ^
      replayedFrom.hashCode ^
      undone.hashCode ^
      note.hashCode ^
      forcedVault.hashCode ^
      models.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode ^
      costUsd.hashCode ^
      route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Operation &&
          runtimeType == other.runtimeType &&
          opId == other.opId &&
          kind == other.kind &&
          summary == other.summary &&
          startedAt == other.startedAt &&
          device == other.device &&
          vaults == other.vaults &&
          pagesCreated == other.pagesCreated &&
          pagesUpdated == other.pagesUpdated &&
          claimsAdded == other.claimsAdded &&
          sources == other.sources &&
          reverts == other.reverts &&
          replayedFrom == other.replayedFrom &&
          undone == other.undone &&
          note == other.note &&
          forcedVault == other.forcedVault &&
          models == other.models &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          costUsd == other.costUsd &&
          route == other.route;
}

enum PageChange { added, modified, deleted }

class PageDiff {
  final String path;
  final PageChange change;
  final List<DiffLine> lines;

  const PageDiff({
    required this.path,
    required this.change,
    required this.lines,
  });

  @override
  int get hashCode => path.hashCode ^ change.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageDiff &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          change == other.change &&
          lines == other.lines;
}

enum ReviewAction { confirm, reject, dismiss }

class ReviewCardDto {
  final String id;
  final CardKind kind;
  final String createdAt;
  final String? opId;

  /// Page the card is about (claims, conflicts), if any.
  final String? page;
  final ClaimInfo? claim;
  final ClaimInfo? replaces;

  /// Routing cards: the vaults the capture went to and the capture id.
  final List<String> vaults;
  final String? rawId;

  /// Question cards and anything else: the text to show.
  final String? text;

  const ReviewCardDto({
    required this.id,
    required this.kind,
    required this.createdAt,
    this.opId,
    this.page,
    this.claim,
    this.replaces,
    required this.vaults,
    this.rawId,
    this.text,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      createdAt.hashCode ^
      opId.hashCode ^
      page.hashCode ^
      claim.hashCode ^
      replaces.hashCode ^
      vaults.hashCode ^
      rawId.hashCode ^
      text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewCardDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          createdAt == other.createdAt &&
          opId == other.opId &&
          page == other.page &&
          claim == other.claim &&
          replaces == other.replaces &&
          vaults == other.vaults &&
          rawId == other.rawId &&
          text == other.text;
}

class RouteTarget {
  final String vault;
  final String reason;
  final double confidence;

  const RouteTarget({
    required this.vault,
    required this.reason,
    required this.confidence,
  });

  @override
  int get hashCode => vault.hashCode ^ reason.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteTarget &&
          runtimeType == other.runtimeType &&
          vault == other.vault &&
          reason == other.reason &&
          confidence == other.confidence;
}

enum UndoResult {
  done,

  /// Later changes overlap; a compensating op runs with the AI jobs.
  queued,
}
