// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Characters of an imported document that are filed at most.
int importCharLimit() => RustLib.instance.api.crateApiImportImportCharLimit();

/// Reads the file at `path` for preview. Audio files are recognised (and size-checked) but not
/// read: they are transcribed after filing.
Future<ImportPreview> readImport({required String path}) =>
    RustLib.instance.api.crateApiImportReadImport(path: path);

enum ImportKind { text, markdown, html, rtf, docx, odt, pptx, epub, pdf, audio }

class ImportPreview {
  final ImportKind kind;
  final String name;

  /// The text that will be filed; empty for audio.
  final String text;

  /// Characters in the whole document before the import limit.
  final int totalChars;

  /// Whether only the first part will be filed.
  final bool truncated;

  /// Pages (PDF) or slides (PPTX).
  final int? pages;

  /// A non-UTF-8 text encoding that was detected, such as "windows-1256".
  final String? encoding;
  final BigInt bytes;

  const ImportPreview({
    required this.kind,
    required this.name,
    required this.text,
    required this.totalChars,
    required this.truncated,
    this.pages,
    this.encoding,
    required this.bytes,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      name.hashCode ^
      text.hashCode ^
      totalChars.hashCode ^
      truncated.hashCode ^
      pages.hashCode ^
      encoding.hashCode ^
      bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportPreview &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          name == other.name &&
          text == other.text &&
          totalChars == other.totalChars &&
          truncated == other.truncated &&
          pages == other.pages &&
          encoding == other.encoding &&
          bytes == other.bytes;
}
