// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

CoreInfo coreInfo() => RustLib.instance.api.crateApiInfoCoreInfo();

/// Build information of the linked core, shown in Settings › About.
class CoreInfo {
  final String appName;
  final String version;
  final int repoSchemaVersion;
  final String target;

  const CoreInfo({
    required this.appName,
    required this.version,
    required this.repoSchemaVersion,
    required this.target,
  });

  @override
  int get hashCode =>
      appName.hashCode ^
      version.hashCode ^
      repoSchemaVersion.hashCode ^
      target.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreInfo &&
          runtimeType == other.runtimeType &&
          appName == other.appName &&
          version == other.version &&
          repoSchemaVersion == other.repoSchemaVersion &&
          target == other.target;
}
