// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ai.dart';
import 'ask.dart';
import 'audit.dart';
import 'mcp.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'reflect.dart';
import 'voice.dart';
import 'wiki.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `human_error`, `now`, `session_arc`, `session`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Whether `root` already holds a library with a named device.
bool libraryReady({required String root}) =>
    RustLib.instance.api.crateApiLibraryLibraryReady(root: root);

/// New library on this device only; a remote can be added later.
Future<void> initLibrary({
  required String root,
  required String deviceName,
  required String platform,
}) => RustLib.instance.api.crateApiLibraryInitLibrary(
  root: root,
  deviceName: deviceName,
  platform: platform,
);

/// Clones (or initialises an empty) remote into `root`.
Future<void> cloneLibrary({
  required String url,
  required String root,
  required Auth auth,
  required String branch,
  required String deviceName,
  required String platform,
}) => RustLib.instance.api.crateApiLibraryCloneLibrary(
  url: url,
  root: root,
  auth: auth,
  branch: branch,
  deviceName: deviceName,
  platform: platform,
);

Future<SshKeyPair> generateSshKey({required String comment}) =>
    RustLib.instance.api.crateApiLibraryGenerateSshKey(comment: comment);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibraryHandle>>
abstract class LibraryHandle implements RustOpaqueInterface {
  /// Operations newest first; pass the last op id seen as `before` to page.
  Future<List<Operation>> activity({required int limit, String? before});

  Future<AiSettings> aiSettings();

  /// Streams `Delta`s, then exactly one `Done` or `Failed`.
  Stream<AskEvent> ask({
    required List<AskTurn> history,
    required String question,
    AskImage? image,
    required AskScopeDto scopeDto,
    required List<ApiKey> apiKeys,
    required List<McpSecret> mcpSecrets,
  });

  Future<String> capturePhoto({
    required List<int> bytes,
    String? note,
    String? vaultHint,
  });

  Future<String> captureText({required String text, String? vaultHint});

  Future<String> captureVoice({required String audioPath, String? vaultHint});

  Future<void> clearRole({required ModelRole role});

  /// Captures of the given local date, oldest first.
  Future<List<Capture>> day({
    required int year,
    required int month,
    required int day,
  });

  Future<bool> discard({required String id});

  /// Files an excluded capture again.
  Future<void> includeCapture({required String rawId});

  /// Settings › Check the wiki now (code checks only; model checks run with the jobs).
  Future<LintSummary> lintNow();

  /// One level of the page tree, e.g. `vaults/life` or `vaults/life/people`.
  Future<Listing> listDir({required String dir});

  Future<LocalGraph> localGraph({required String path, required int depth});

  /// Connects once to report status and tools (§10 server list).
  Future<McpStatus> mcpCheck({required String id, required String secretsJson});

  /// Starts OAuth (§10). With no `redirect_uri` (desktop) a loopback listener on 127.0.0.1 is
  /// used; call `mcp_oauth_wait`. On mobile pass `daftar://oauth/callback` and hand the redirect
  /// to `mcp_oauth_complete`. The app opens `auth_url` in the system browser.
  Future<OAuthStart> mcpOauthBegin({
    required String id,
    required String secretsJson,
    String? redirectUri,
  });

  /// Finishes OAuth with the redirect URL; returns the new secrets JSON for this server.
  Future<String> mcpOauthComplete({
    required String flowId,
    required String callbackUrl,
  });

  /// Desktop: waits for the browser to come back to the loopback listener. Returns the new
  /// secrets JSON for this server.
  Future<String> mcpOauthWait({required String flowId});

  Future<List<McpServer>> mcpServers();

  Future<UndoResult> moveToVault({required String opId, required String vault});

  static Future<LibraryHandle> open({required String root}) =>
      RustLib.instance.api.crateApiLibraryLibraryHandleOpen(root: root);

  Future<Operation> operation({required String opId});

  Future<List<PageDiff>> operationDiff({required String opId});

  Future<WikiPage> page({required String path});

  /// Settings › Repository › Rebuild index.
  Future<int> rebuildIndex();

  Future<List<PageSummary>> recentPages({String? vault, required int limit});

  Future<ReflectPrefs> reflectPrefs();

  /// Picks up files changed outside the app (on resume and after sync).
  Future<int> refreshIndex();

  Future<void> removeMcpServer({required String id});

  /// Removes a provider and the roles that used it. The app deletes its key from secure storage.
  Future<void> removeProvider({required String id});

  Future<UndoResult> rerunWithNote({
    required String opId,
    required String note,
  });

  /// Where a wikilink points (`sara`, `people/sara`, `raw/2026/09/23/…`), if it exists.
  Future<String?> resolveLink({required String target});

  /// `edited_text` only with `Confirm`: the user's corrected wording of the claim.
  Future<void> resolveReview({
    required String cardId,
    required ReviewAction action,
    String? editedText,
  });

  /// Makes a failed capture's jobs runnable again (the Retry action on a failed capture).
  Future<void> retryCapture({required String rawId});

  Future<List<ReviewCardDto>> reviewCards();

  /// Runs queued AI jobs (transcribe, describe, ingest) until the queue is empty or blocked.
  Future<RunSummary> runJobs({
    required List<ApiKey> apiKeys,
    required bool online,
  });

  /// "Save to wiki": files the question and answer through the normal pipeline.
  Future<String> saveAnswer({
    required String question,
    required String answer,
    required AskScopeDto scopeDto,
  });

  /// Story mode: saves a draft under `drafts/`; returns its path.
  Future<String> saveDraft({
    required String story,
    required String title,
    required String text,
  });

  /// Adds or updates a server; returns its id.
  Future<String> saveMcpServer({required McpServer server});

  /// Saves an edit as one human commit; fails if the page changed since `base_hash`.
  Future<SaveResult> savePage({
    required String path,
    required String baseHash,
    required String text,
  });

  /// Adds or updates a provider; returns its id (new providers get one).
  Future<String> saveProvider({required AiProvider provider});

  /// Queues what is due now (reflections, and lint when enough was filed). Returns how many jobs.
  Future<int> scheduleDue();

  Future<List<SearchHit>> search({
    required String query,
    required List<String> vaults,
    required int limit,
  });

  Future<void> setReflectPrefs({required ReflectPrefs prefs});

  Future<void> setRemote({required String url});

  Future<void> setRole({
    required ModelRole role,
    required String providerId,
    required String model,
  });

  /// Starts a voice conversation; listen with `VoiceHandle::events`.
  Future<VoiceHandle> startVoice({
    required VoiceOptions options,
    required List<ApiKey> apiKeys,
  });

  Future<RepoStatus> status();

  Future<SyncResult> sync_({required Auth auth});

  Future<ReflectSignals> takeReflectSignals();

  /// The Test button: one real minimal call for the role as configured, with its latency.
  /// A failure is an outcome, not an error, so the app can show it next to the role.
  Future<ProbeOutcome> testRole({
    required ModelRole role,
    required List<ApiKey> apiKeys,
  });

  /// Undo (and Exclude source): the capture stays in raw/ as excluded.
  Future<UndoResult> undo({required String opId});

  Future<List<Vault>> vaults();
}

/// Credentials for one call. Loaded from secure storage by the app; never persisted by the core.
class Auth {
  final AuthKind kind;
  final String? username;

  /// Token for `Token`, OpenSSH private key text for `SshKey`.
  final String secret;
  final String? passphrase;

  const Auth({
    required this.kind,
    this.username,
    required this.secret,
    this.passphrase,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ username.hashCode ^ secret.hashCode ^ passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Auth &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          username == other.username &&
          secret == other.secret &&
          passphrase == other.passphrase;
}

enum AuthKind { none, token, sshKey }

class Capture {
  final String id;
  final RawKind kind;

  /// RFC 3339 with offset.
  final String capturedAt;
  final String device;
  final String text;
  final String? vaultHint;
  final List<String> images;
  final Stage stage;
  final String? problem;
  final Filing? filing;

  const Capture({
    required this.id,
    required this.kind,
    required this.capturedAt,
    required this.device,
    required this.text,
    this.vaultHint,
    required this.images,
    required this.stage,
    this.problem,
    this.filing,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      capturedAt.hashCode ^
      device.hashCode ^
      text.hashCode ^
      vaultHint.hashCode ^
      images.hashCode ^
      stage.hashCode ^
      problem.hashCode ^
      filing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Capture &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          capturedAt == other.capturedAt &&
          device == other.device &&
          text == other.text &&
          vaultHint == other.vaultHint &&
          images == other.images &&
          stage == other.stage &&
          problem == other.problem &&
          filing == other.filing;
}

/// What filing did for a capture: "Filed to Life · Health — 4 pages updated, 1 claim to review".
class Filing {
  final String opId;
  final List<String> vaults;
  final int pagesCreated;
  final int pagesUpdated;
  final int claimsToReview;
  final int toReview;

  const Filing({
    required this.opId,
    required this.vaults,
    required this.pagesCreated,
    required this.pagesUpdated,
    required this.claimsToReview,
    required this.toReview,
  });

  @override
  int get hashCode =>
      opId.hashCode ^
      vaults.hashCode ^
      pagesCreated.hashCode ^
      pagesUpdated.hashCode ^
      claimsToReview.hashCode ^
      toReview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Filing &&
          runtimeType == other.runtimeType &&
          opId == other.opId &&
          vaults == other.vaults &&
          pagesCreated == other.pagesCreated &&
          pagesUpdated == other.pagesUpdated &&
          claimsToReview == other.claimsToReview &&
          toReview == other.toReview;
}

enum RawKind { voice, text, photo, voiceConversation, chatAnswer, import_ }

class RepoStatus {
  final int uncommitted;
  final int unpushed;
  final bool hasRemote;
  final String branch;
  final String? remoteUrl;
  final String deviceId;
  final String deviceName;
  final String root;

  const RepoStatus({
    required this.uncommitted,
    required this.unpushed,
    required this.hasRemote,
    required this.branch,
    this.remoteUrl,
    required this.deviceId,
    required this.deviceName,
    required this.root,
  });

  @override
  int get hashCode =>
      uncommitted.hashCode ^
      unpushed.hashCode ^
      hasRemote.hashCode ^
      branch.hashCode ^
      remoteUrl.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepoStatus &&
          runtimeType == other.runtimeType &&
          uncommitted == other.uncommitted &&
          unpushed == other.unpushed &&
          hasRemote == other.hasRemote &&
          branch == other.branch &&
          remoteUrl == other.remoteUrl &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          root == other.root;
}

class SshKeyPair {
  final String privateOpenssh;
  final String publicOpenssh;

  const SshKeyPair({required this.privateOpenssh, required this.publicOpenssh});

  @override
  int get hashCode => privateOpenssh.hashCode ^ publicOpenssh.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshKeyPair &&
          runtimeType == other.runtimeType &&
          privateOpenssh == other.privateOpenssh &&
          publicOpenssh == other.publicOpenssh;
}

enum Stage { saved, working, failed, filed, excluded }

class SyncResult {
  final SyncState state;
  final String? message;
  final int pulled;
  final int pushed;
  final List<String> conflicts;
  final int replays;
  final List<String> changedPaths;

  const SyncResult({
    required this.state,
    this.message,
    required this.pulled,
    required this.pushed,
    required this.conflicts,
    required this.replays,
    required this.changedPaths,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      message.hashCode ^
      pulled.hashCode ^
      pushed.hashCode ^
      conflicts.hashCode ^
      replays.hashCode ^
      changedPaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResult &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          message == other.message &&
          pulled == other.pulled &&
          pushed == other.pushed &&
          conflicts == other.conflicts &&
          replays == other.replays &&
          changedPaths == other.changedPaths;
}

enum SyncState { synced, localChanges, offline, needsAttention }

class Vault {
  final String id;
  final String titleEn;
  final String titleFa;
  final bool fiction;

  const Vault({
    required this.id,
    required this.titleEn,
    required this.titleFa,
    required this.fiction,
  });

  @override
  int get hashCode =>
      id.hashCode ^ titleEn.hashCode ^ titleFa.hashCode ^ fiction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Vault &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          titleEn == other.titleEn &&
          titleFa == other.titleFa &&
          fiction == other.fiction;
}
