// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `human_error`, `now`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Whether `root` already holds a library with a named device.
bool libraryReady({required String root}) =>
    RustLib.instance.api.crateApiLibraryLibraryReady(root: root);

/// New library on this device only; a remote can be added later.
Future<void> initLibrary({
  required String root,
  required String deviceName,
  required String platform,
}) => RustLib.instance.api.crateApiLibraryInitLibrary(
  root: root,
  deviceName: deviceName,
  platform: platform,
);

/// Clones (or initialises an empty) remote into `root`.
Future<void> cloneLibrary({
  required String url,
  required String root,
  required Auth auth,
  required String branch,
  required String deviceName,
  required String platform,
}) => RustLib.instance.api.crateApiLibraryCloneLibrary(
  url: url,
  root: root,
  auth: auth,
  branch: branch,
  deviceName: deviceName,
  platform: platform,
);

Future<SshKeyPair> generateSshKey({required String comment}) =>
    RustLib.instance.api.crateApiLibraryGenerateSshKey(comment: comment);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibraryHandle>>
abstract class LibraryHandle implements RustOpaqueInterface {
  Future<String> capturePhoto({
    required List<int> bytes,
    String? note,
    String? vaultHint,
  });

  Future<String> captureText({required String text, String? vaultHint});

  Future<String> captureVoice({required String audioPath, String? vaultHint});

  /// Captures of the given local date, oldest first.
  Future<List<Capture>> day({
    required int year,
    required int month,
    required int day,
  });

  Future<bool> discard({required String id});

  static Future<LibraryHandle> open({required String root}) =>
      RustLib.instance.api.crateApiLibraryLibraryHandleOpen(root: root);

  Future<void> setRemote({required String url});

  Future<RepoStatus> status();

  Future<SyncResult> sync_({required Auth auth});

  Future<List<Vault>> vaults();
}

/// Credentials for one call. Loaded from secure storage by the app; never persisted by the core.
class Auth {
  final AuthKind kind;
  final String? username;

  /// Token for `Token`, OpenSSH private key text for `SshKey`.
  final String secret;
  final String? passphrase;

  const Auth({
    required this.kind,
    this.username,
    required this.secret,
    this.passphrase,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ username.hashCode ^ secret.hashCode ^ passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Auth &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          username == other.username &&
          secret == other.secret &&
          passphrase == other.passphrase;
}

enum AuthKind { none, token, sshKey }

class Capture {
  final String id;
  final RawKind kind;

  /// RFC 3339 with offset.
  final String capturedAt;
  final String device;
  final String text;
  final String? vaultHint;
  final List<String> images;
  final Stage stage;
  final String? problem;

  const Capture({
    required this.id,
    required this.kind,
    required this.capturedAt,
    required this.device,
    required this.text,
    this.vaultHint,
    required this.images,
    required this.stage,
    this.problem,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      capturedAt.hashCode ^
      device.hashCode ^
      text.hashCode ^
      vaultHint.hashCode ^
      images.hashCode ^
      stage.hashCode ^
      problem.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Capture &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          capturedAt == other.capturedAt &&
          device == other.device &&
          text == other.text &&
          vaultHint == other.vaultHint &&
          images == other.images &&
          stage == other.stage &&
          problem == other.problem;
}

enum RawKind { voice, text, photo, voiceConversation, chatAnswer, import_ }

class RepoStatus {
  final int uncommitted;
  final int unpushed;
  final bool hasRemote;
  final String branch;
  final String? remoteUrl;
  final String deviceId;
  final String deviceName;
  final String root;

  const RepoStatus({
    required this.uncommitted,
    required this.unpushed,
    required this.hasRemote,
    required this.branch,
    this.remoteUrl,
    required this.deviceId,
    required this.deviceName,
    required this.root,
  });

  @override
  int get hashCode =>
      uncommitted.hashCode ^
      unpushed.hashCode ^
      hasRemote.hashCode ^
      branch.hashCode ^
      remoteUrl.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepoStatus &&
          runtimeType == other.runtimeType &&
          uncommitted == other.uncommitted &&
          unpushed == other.unpushed &&
          hasRemote == other.hasRemote &&
          branch == other.branch &&
          remoteUrl == other.remoteUrl &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          root == other.root;
}

class SshKeyPair {
  final String privateOpenssh;
  final String publicOpenssh;

  const SshKeyPair({required this.privateOpenssh, required this.publicOpenssh});

  @override
  int get hashCode => privateOpenssh.hashCode ^ publicOpenssh.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshKeyPair &&
          runtimeType == other.runtimeType &&
          privateOpenssh == other.privateOpenssh &&
          publicOpenssh == other.publicOpenssh;
}

enum Stage { saved, working, failed, filed, excluded }

class SyncResult {
  final SyncState state;
  final String? message;
  final int pulled;
  final int pushed;
  final List<String> conflicts;
  final int replays;
  final List<String> changedPaths;

  const SyncResult({
    required this.state,
    this.message,
    required this.pulled,
    required this.pushed,
    required this.conflicts,
    required this.replays,
    required this.changedPaths,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      message.hashCode ^
      pulled.hashCode ^
      pushed.hashCode ^
      conflicts.hashCode ^
      replays.hashCode ^
      changedPaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResult &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          message == other.message &&
          pulled == other.pulled &&
          pushed == other.pushed &&
          conflicts == other.conflicts &&
          replays == other.replays &&
          changedPaths == other.changedPaths;
}

enum SyncState { synced, localChanges, offline, needsAttention }

class Vault {
  final String id;
  final String titleEn;
  final String titleFa;
  final bool fiction;

  const Vault({
    required this.id,
    required this.titleEn,
    required this.titleFa,
    required this.fiction,
  });

  @override
  int get hashCode =>
      id.hashCode ^ titleEn.hashCode ^ titleFa.hashCode ^ fiction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Vault &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          titleEn == other.titleEn &&
          titleFa == other.titleFa &&
          fiction == other.fiction;
}
