// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `flows`, `from_config`, `pending`, `secrets_of`, `to_config`, `toolset`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AppApprover`, `Flow`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `approve`

/// Whether local (stdio) servers can run on this device.
bool mcpStdioSupported() => RustLib.instance.api.crateApiMcpMcpStdioSupported();

/// The user's answer to a tool approval card.
void answerToolApproval({required String requestId, required bool allowed}) =>
    RustLib.instance.api.crateApiMcpAnswerToolApproval(
      requestId: requestId,
      allowed: allowed,
    );

enum McpAuthKind {
  none,
  bearer,
  apiKeyHeader,
  apiKeyQuery,
  headers,
  oAuth,
  clientCredentials,
}

enum McpPolicy { askEveryTime, autoReadOnly, alwaysAllow }

class McpServer {
  /// Empty when adding.
  final String id;
  final String name;
  final McpTransportKind transport;

  /// URL for HTTP transports, the command for stdio.
  final String target;
  final List<String> args;
  final List<String> envNames;
  final McpAuthKind auth;

  /// Header or query parameter name (API key), header names (custom headers).
  final List<String> authNames;

  /// OAuth / client credentials client id; empty = dynamic registration.
  final String clientId;
  final List<String> scopes;
  final McpPolicy policy;
  final bool enabled;

  const McpServer({
    required this.id,
    required this.name,
    required this.transport,
    required this.target,
    required this.args,
    required this.envNames,
    required this.auth,
    required this.authNames,
    required this.clientId,
    required this.scopes,
    required this.policy,
    required this.enabled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      transport.hashCode ^
      target.hashCode ^
      args.hashCode ^
      envNames.hashCode ^
      auth.hashCode ^
      authNames.hashCode ^
      clientId.hashCode ^
      scopes.hashCode ^
      policy.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McpServer &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          transport == other.transport &&
          target == other.target &&
          args == other.args &&
          envNames == other.envNames &&
          auth == other.auth &&
          authNames == other.authNames &&
          clientId == other.clientId &&
          scopes == other.scopes &&
          policy == other.policy &&
          enabled == other.enabled;
}

class McpStatus {
  final McpStatusKind kind;
  final String? message;
  final List<McpToolInfo> tools;

  /// Refreshed credentials to write back to secure storage (JSON), if they changed.
  final String? updatedSecrets;

  const McpStatus({
    required this.kind,
    this.message,
    required this.tools,
    this.updatedSecrets,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      message.hashCode ^
      tools.hashCode ^
      updatedSecrets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McpStatus &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          tools == other.tools &&
          updatedSecrets == other.updatedSecrets;
}

enum McpStatusKind { connected, needsAuth, desktopOnly, error, disabled }

class McpToolInfo {
  final String name;
  final String description;
  final bool readOnly;

  const McpToolInfo({
    required this.name,
    required this.description,
    required this.readOnly,
  });

  @override
  int get hashCode => name.hashCode ^ description.hashCode ^ readOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McpToolInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          readOnly == other.readOnly;
}

enum McpTransportKind { streamableHttp, sse, stdio }

class OAuthStart {
  final String flowId;
  final String authUrl;

  const OAuthStart({required this.flowId, required this.authUrl});

  @override
  int get hashCode => flowId.hashCode ^ authUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OAuthStart &&
          runtimeType == other.runtimeType &&
          flowId == other.flowId &&
          authUrl == other.authUrl;
}
