// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`

class LintSummary {
  final int findings;
  final int newCards;

  const LintSummary({required this.findings, required this.newCards});

  @override
  int get hashCode => findings.hashCode ^ newCards.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LintSummary &&
          runtimeType == other.runtimeType &&
          findings == other.findings &&
          newCards == other.newCards;
}

class ReflectPrefs {
  final bool daily;

  /// "HH:MM", local time.
  final String dailyTime;
  final bool weekly;

  /// 1 = Monday … 7 = Sunday.
  final int weeklyDay;
  final bool notifications;

  /// ISO country for the helpline card ("" = international).
  final String helplineCountry;

  const ReflectPrefs({
    required this.daily,
    required this.dailyTime,
    required this.weekly,
    required this.weeklyDay,
    required this.notifications,
    required this.helplineCountry,
  });

  @override
  int get hashCode =>
      daily.hashCode ^
      dailyTime.hashCode ^
      weekly.hashCode ^
      weeklyDay.hashCode ^
      notifications.hashCode ^
      helplineCountry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReflectPrefs &&
          runtimeType == other.runtimeType &&
          daily == other.daily &&
          dailyTime == other.dailyTime &&
          weekly == other.weekly &&
          weeklyDay == other.weeklyDay &&
          notifications == other.notifications &&
          helplineCountry == other.helplineCountry;
}

class ReflectSignals {
  /// Local notifications to show (at most three lines each, never sensitive).
  final List<String> notifications;

  /// A reflection saw signs of crisis: show the Talk to someone card.
  final bool needsHelp;

  const ReflectSignals({required this.notifications, required this.needsHelp});

  @override
  int get hashCode => notifications.hashCode ^ needsHelp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReflectSignals &&
          runtimeType == other.runtimeType &&
          notifications == other.notifications &&
          needsHelp == other.needsHelp;
}
