// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`

class VaultSettings {
  final String id;
  final String titleEn;
  final String titleFa;

  /// What belongs in the vault; the assistant files by it.
  final String purpose;
  final bool archived;
  final bool fiction;

  /// Life and Stories: can be renamed, never archived or removed.
  final bool builtin;

  /// Pages in the vault; only an empty vault can be removed.
  final int pages;

  const VaultSettings({
    required this.id,
    required this.titleEn,
    required this.titleFa,
    required this.purpose,
    required this.archived,
    required this.fiction,
    required this.builtin,
    required this.pages,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      titleEn.hashCode ^
      titleFa.hashCode ^
      purpose.hashCode ^
      archived.hashCode ^
      fiction.hashCode ^
      builtin.hashCode ^
      pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultSettings &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          titleEn == other.titleEn &&
          titleFa == other.titleFa &&
          purpose == other.purpose &&
          archived == other.archived &&
          fiction == other.fiction &&
          builtin == other.builtin &&
          pages == other.pages;
}
