// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dto`, `ev`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VoiceHandle>>
abstract class VoiceHandle implements RustOpaqueInterface {
  /// Ends the conversation; returns the id of the saved transcript capture, if any.
  Future<String?> end();

  /// Microphone PCM, mono 16-bit at the session's sample rate.
  Future<void> feed({required List<int> pcm});

  Future<void> playbackFinished();

  Future<void> setMuted({required bool muted});
}

class VoiceEventDto {
  final VoiceEventKind kind;
  final VoiceStateDto? state;

  /// Caption text, captured raw id, or error sentence.
  final String? text;
  final BigInt seq;
  final String? lang;
  final Uint8List? bytes;

  const VoiceEventDto({
    required this.kind,
    this.state,
    this.text,
    required this.seq,
    this.lang,
    this.bytes,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      state.hashCode ^
      text.hashCode ^
      seq.hashCode ^
      lang.hashCode ^
      bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          state == other.state &&
          text == other.text &&
          seq == other.seq &&
          lang == other.lang &&
          bytes == other.bytes;
}

enum VoiceEventKind {
  state,
  userCaption,
  assistantCaption,

  /// Encoded audio for one sentence (format as returned by the TTS provider, usually MP3).
  audio,
  stopPlayback,
  needsHelp,
  captured,
  error,
}

class VoiceOptions {
  final int sampleRate;

  /// Silence that ends an utterance, in ms (default 700).
  final int silenceMs;

  /// 0 (least) … 1 (most sensitive); default 0.5.
  final double sensitivity;
  final bool saveTranscript;

  const VoiceOptions({
    required this.sampleRate,
    required this.silenceMs,
    required this.sensitivity,
    required this.saveTranscript,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^
      silenceMs.hashCode ^
      sensitivity.hashCode ^
      saveTranscript.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceOptions &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          silenceMs == other.silenceMs &&
          sensitivity == other.sensitivity &&
          saveTranscript == other.saveTranscript;
}

enum VoiceStateDto { listening, hearing, thinking, speaking, muted }
