// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `summary`

class FolderEntry {
  final String path;
  final int pages;

  const FolderEntry({required this.path, required this.pages});

  @override
  int get hashCode => path.hashCode ^ pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          pages == other.pages;
}

class GraphEdge {
  final String from;
  final String to;

  const GraphEdge({required this.from, required this.to});

  @override
  int get hashCode => from.hashCode ^ to.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphEdge &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to;
}

class GraphNode {
  final PageSummary page;
  final int depth;

  const GraphNode({required this.page, required this.depth});

  @override
  int get hashCode => page.hashCode ^ depth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphNode &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          depth == other.depth;
}

class Listing {
  final List<FolderEntry> folders;
  final List<PageSummary> pages;

  const Listing({required this.folders, required this.pages});

  @override
  int get hashCode => folders.hashCode ^ pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Listing &&
          runtimeType == other.runtimeType &&
          folders == other.folders &&
          pages == other.pages;
}

class LocalGraph {
  final List<GraphNode> nodes;
  final List<GraphEdge> edges;

  const LocalGraph({required this.nodes, required this.edges});

  @override
  int get hashCode => nodes.hashCode ^ edges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalGraph &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes &&
          edges == other.edges;
}

class PageSummary {
  final String path;
  final String vault;
  final String kind;
  final String titleEn;
  final String titleFa;
  final String summary;
  final String updated;

  const PageSummary({
    required this.path,
    required this.vault,
    required this.kind,
    required this.titleEn,
    required this.titleFa,
    required this.summary,
    required this.updated,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      vault.hashCode ^
      kind.hashCode ^
      titleEn.hashCode ^
      titleFa.hashCode ^
      summary.hashCode ^
      updated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageSummary &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          vault == other.vault &&
          kind == other.kind &&
          titleEn == other.titleEn &&
          titleFa == other.titleFa &&
          summary == other.summary &&
          updated == other.updated;
}

class SaveResult {
  final String hash;
  final bool committed;

  const SaveResult({required this.hash, required this.committed});

  @override
  int get hashCode => hash.hashCode ^ committed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveResult &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          committed == other.committed;
}

class SearchHit {
  final PageSummary page;

  /// A line of the page around the first match, as written.
  final String snippet;

  const SearchHit({required this.page, required this.snippet});

  @override
  int get hashCode => page.hashCode ^ snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          snippet == other.snippet;
}

/// The whole wiki as a graph. Edges hold indexes into `nodes`, one per linked pair.
class WikiGraph {
  final List<WikiGraphNode> nodes;
  final Uint32List edgeFrom;
  final Uint32List edgeTo;

  const WikiGraph({
    required this.nodes,
    required this.edgeFrom,
    required this.edgeTo,
  });

  @override
  int get hashCode => nodes.hashCode ^ edgeFrom.hashCode ^ edgeTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WikiGraph &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes &&
          edgeFrom == other.edgeFrom &&
          edgeTo == other.edgeTo;
}

/// A page in the whole-wiki graph, with the number of distinct pages it is linked with.
class WikiGraphNode {
  final PageSummary page;
  final int links;

  const WikiGraphNode({required this.page, required this.links});

  @override
  int get hashCode => page.hashCode ^ links.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WikiGraphNode &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          links == other.links;
}

class WikiPage {
  final String path;

  /// The whole file, for the source editor.
  final String text;

  /// Markdown after the frontmatter, for the renderer.
  final String body;
  final String hash;
  final String kind;
  final String vault;
  final String titleEn;
  final String titleFa;
  final List<String> aliases;
  final String summary;
  final String updated;
  final String status;
  final int sourceCount;
  final List<PageSummary> backlinks;

  const WikiPage({
    required this.path,
    required this.text,
    required this.body,
    required this.hash,
    required this.kind,
    required this.vault,
    required this.titleEn,
    required this.titleFa,
    required this.aliases,
    required this.summary,
    required this.updated,
    required this.status,
    required this.sourceCount,
    required this.backlinks,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      text.hashCode ^
      body.hashCode ^
      hash.hashCode ^
      kind.hashCode ^
      vault.hashCode ^
      titleEn.hashCode ^
      titleFa.hashCode ^
      aliases.hashCode ^
      summary.hashCode ^
      updated.hashCode ^
      status.hashCode ^
      sourceCount.hashCode ^
      backlinks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WikiPage &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          text == other.text &&
          body == other.body &&
          hash == other.hash &&
          kind == other.kind &&
          vault == other.vault &&
          titleEn == other.titleEn &&
          titleFa == other.titleFa &&
          aliases == other.aliases &&
          summary == other.summary &&
          updated == other.updated &&
          status == other.status &&
          sourceCount == other.sourceCount &&
          backlinks == other.backlinks;
}
